# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Your Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email Addr')),
                ('parent_comment', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost')),
            ],
        ),
    ]
