# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
